ifeq ($(CONFIG_OF),y)

dtb-$(CONFIG_SOC_IMX6Q) += \
	imx6q-rev-sa01-pfuze100.dtb \
	imx6solo-rev-sa01-pfuze100.dtb \
	imx6q-rev-sa01-wm8326.dtb \
	imx6solo-rev-sa01-wm8326.dtb
endif

always		:= $(dtb-y)
clean-files	:= *.dtb
